### ISSUE TITLE
Cannot share folder outside of Mechfile folder

### ISSUE THREAD

**Issue by nhubaotruong** [mkinney/mech#22]
Can I share folder outside of the folder that contains Mechfile?

I like to use mech because it is so much faster than vagrant with virtualbox, please help.

**Comment by mkinney** [comment]
Sorry, I didn't see that an issue was created until now.

Thanks for using mech!

Yes, you should be able to share any folder. (note: I found sharing /tmp on mac did create a weird issue where you need to preface with "/private" first.)

See https://github.com/mkinney/mech/blob/master/tests/int/shared_folders/Mechfile#L12 for an example how you can share out a different folder. If it is not clear, let me know.

**Comment by nhubaotruong** [comment]
Sorry, I haven't got any answer for so long, so I've switch to using wsl 2. I'll try again when possible. Does mech support port forwarding like vagrant ?

**Comment by mkinney** [comment]
What is "wsl 2"?

Port forwarding is not implemented. But, "no-nat" networking might work for you. See "mech up --help" for more info or let me know if that does not make sense.

**Comment by nhubaotruong** [comment]
wsl 2 is windows subsystem for linux 2. It's a windows feature. I'll try mech when I reinstall windows

**Comment by mkinney** [comment]
Ok. Mech run on linux and mac, too. (in addition to windows)

Ok to close issue?

**Comment by nhubaotruong** [comment]
Yes, I'll close it now
